[GLOBAL]
pants_version = "2.21.0"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.10.12"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]
